on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: KronHUD-Beta
          path: build/libs/
      - name: Get Commit SHA
        id: short_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Release Files
        uses: softprops/action-gh-release@v1
        with: 
          token: ${{ secrets.RELEASE_KEY }}
          files: |
            build/libs/*.jar
          tag_name: commit-${{ steps.short_sha.outputs.sha_short }}
          name: KronHUD Automation Compile ${{ steps.short_sha.outputs.sha_short }}
          body: |
            Commit ${{ steps.short_sha.outputs.sha_short }}
            This is an automated release, it have not been tested yet.
            This release will trigger whenever a Git push happens to the project.
            It will also upload an artifact. But artifacts require an GitHub account.
            Build Type: Beta Builds
          generate_release_notes: true
        env:
          GITHUB_REPOSITORY: MediumCraft/KronHUD
